name: Create release with Semantic Version tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build Linux
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-linux-x64"

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_name"

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Build Windows
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-win-x64"

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_name"

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Build MacOS
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-osx-x64"

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_name"

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Build MacOSarm
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-osx-arm64"

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-arm64" -c Release -o "$release_name"

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Chirp-v*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
